//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admination
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetails
    {
        public int Id { get; set; }
        public Nullable<int> Id_Cart { get; set; }
        public Nullable<int> Id_Bou { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
    
        public virtual Bouquest Bouquest { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
