//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admination
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int Id { get; set; }
        public Nullable<int> Id_Bill { get; set; }
        public string Credit_Card { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
