//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admination
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JavaFloristEntities : DbContext
    {
        public JavaFloristEntities()
            : base("name=JavaFloristEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<Bouquest> Bouquest { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CartDetails> CartDetails { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Role> Role { get; set; }
    
        public virtual int ProBill_Create(Nullable<int> id_Bill, Nullable<int> id_Bou, string name, string image, string description, Nullable<decimal> price, Nullable<int> id_Cus, Nullable<int> volume, Nullable<System.DateTime> order_Date, Nullable<System.DateTime> delivery_Date, string cus_Note, string bill_status)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            var id_BouParameter = id_Bou.HasValue ?
                new ObjectParameter("id_Bou", id_Bou) :
                new ObjectParameter("id_Bou", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var id_CusParameter = id_Cus.HasValue ?
                new ObjectParameter("id_Cus", id_Cus) :
                new ObjectParameter("id_Cus", typeof(int));
    
            var volumeParameter = volume.HasValue ?
                new ObjectParameter("volume", volume) :
                new ObjectParameter("volume", typeof(int));
    
            var order_DateParameter = order_Date.HasValue ?
                new ObjectParameter("order_Date", order_Date) :
                new ObjectParameter("order_Date", typeof(System.DateTime));
    
            var delivery_DateParameter = delivery_Date.HasValue ?
                new ObjectParameter("delivery_Date", delivery_Date) :
                new ObjectParameter("delivery_Date", typeof(System.DateTime));
    
            var cus_NoteParameter = cus_Note != null ?
                new ObjectParameter("cus_Note", cus_Note) :
                new ObjectParameter("cus_Note", typeof(string));
    
            var bill_statusParameter = bill_status != null ?
                new ObjectParameter("bill_status", bill_status) :
                new ObjectParameter("bill_status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProBill_Create", id_BillParameter, id_BouParameter, nameParameter, imageParameter, descriptionParameter, priceParameter, id_CusParameter, volumeParameter, order_DateParameter, delivery_DateParameter, cus_NoteParameter, bill_statusParameter);
        }
    
        public virtual ObjectResult<ProBill_ReadAllBillByBouquest_Result> ProBill_ReadAllBillByBouquest(Nullable<int> id_Bou)
        {
            var id_BouParameter = id_Bou.HasValue ?
                new ObjectParameter("id_Bou", id_Bou) :
                new ObjectParameter("id_Bou", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProBill_ReadAllBillByBouquest_Result>("ProBill_ReadAllBillByBouquest", id_BouParameter);
        }
    
        public virtual ObjectResult<ProBill_ReadAllBillByCustomer_Result> ProBill_ReadAllBillByCustomer(Nullable<int> id_Cus)
        {
            var id_CusParameter = id_Cus.HasValue ?
                new ObjectParameter("id_Cus", id_Cus) :
                new ObjectParameter("id_Cus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProBill_ReadAllBillByCustomer_Result>("ProBill_ReadAllBillByCustomer", id_CusParameter);
        }
    
        public virtual int ProBill_UpStt_Canceled(Nullable<int> id_Bill)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProBill_UpStt_Canceled", id_BillParameter);
        }
    
        public virtual int ProBill_UpStt_Delivering(Nullable<int> id_Bill)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProBill_UpStt_Delivering", id_BillParameter);
        }
    
        public virtual int ProBill_UpStt_Done(Nullable<int> id_Bill)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProBill_UpStt_Done", id_BillParameter);
        }
    
        public virtual int ProBill_UpStt_Loading(Nullable<int> id_Bill)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProBill_UpStt_Loading", id_BillParameter);
        }
    
        public virtual int ProBill_UpStt_Other(Nullable<int> id_Bill, string status)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProBill_UpStt_Other", id_BillParameter, statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ProCart_CreateGetId(Nullable<int> id_Cus)
        {
            var id_CusParameter = id_Cus.HasValue ?
                new ObjectParameter("id_Cus", id_Cus) :
                new ObjectParameter("id_Cus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ProCart_CreateGetId", id_CusParameter);
        }
    
        public virtual int ProCart_Update(Nullable<int> id_Cart, Nullable<decimal> total)
        {
            var id_CartParameter = id_Cart.HasValue ?
                new ObjectParameter("id_Cart", id_Cart) :
                new ObjectParameter("id_Cart", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProCart_Update", id_CartParameter, totalParameter);
        }
    
        public virtual int ProCartDetails_Create(Nullable<int> id_Cart, Nullable<int> id_Bou, Nullable<int> volume, Nullable<decimal> total_price)
        {
            var id_CartParameter = id_Cart.HasValue ?
                new ObjectParameter("id_Cart", id_Cart) :
                new ObjectParameter("id_Cart", typeof(int));
    
            var id_BouParameter = id_Bou.HasValue ?
                new ObjectParameter("id_Bou", id_Bou) :
                new ObjectParameter("id_Bou", typeof(int));
    
            var volumeParameter = volume.HasValue ?
                new ObjectParameter("Volume", volume) :
                new ObjectParameter("Volume", typeof(int));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProCartDetails_Create", id_CartParameter, id_BouParameter, volumeParameter, total_priceParameter);
        }
    
        public virtual int ProCartDetails_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProCartDetails_Delete", idParameter);
        }
    
        public virtual ObjectResult<ProCartDetails_Read_Result> ProCartDetails_Read(Nullable<int> id, Nullable<int> id_Cart, Nullable<int> id_Bou, Nullable<int> volume, Nullable<decimal> total_price, string statement)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_CartParameter = id_Cart.HasValue ?
                new ObjectParameter("id_Cart", id_Cart) :
                new ObjectParameter("id_Cart", typeof(int));
    
            var id_BouParameter = id_Bou.HasValue ?
                new ObjectParameter("id_Bou", id_Bou) :
                new ObjectParameter("id_Bou", typeof(int));
    
            var volumeParameter = volume.HasValue ?
                new ObjectParameter("Volume", volume) :
                new ObjectParameter("Volume", typeof(int));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            var statementParameter = statement != null ?
                new ObjectParameter("statement", statement) :
                new ObjectParameter("statement", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProCartDetails_Read_Result>("ProCartDetails_Read", idParameter, id_CartParameter, id_BouParameter, volumeParameter, total_priceParameter, statementParameter);
        }
    
        public virtual int ProCartDetails_Update(Nullable<int> id, Nullable<int> volume, Nullable<decimal> total_price)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var volumeParameter = volume.HasValue ?
                new ObjectParameter("Volume", volume) :
                new ObjectParameter("Volume", typeof(int));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProCartDetails_Update", idParameter, volumeParameter, total_priceParameter);
        }
    
        public virtual int ProCus_Create(string email, string password, string firstName, string lastName, string image, Nullable<System.DateTime> birth, Nullable<int> id_Gender, string phone, string address, Nullable<int> id_Role)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var birthParameter = birth.HasValue ?
                new ObjectParameter("birth", birth) :
                new ObjectParameter("birth", typeof(System.DateTime));
    
            var id_GenderParameter = id_Gender.HasValue ?
                new ObjectParameter("id_Gender", id_Gender) :
                new ObjectParameter("id_Gender", typeof(int));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var id_RoleParameter = id_Role.HasValue ?
                new ObjectParameter("id_Role", id_Role) :
                new ObjectParameter("id_Role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProCus_Create", emailParameter, passwordParameter, firstNameParameter, lastNameParameter, imageParameter, birthParameter, id_GenderParameter, phoneParameter, addressParameter, id_RoleParameter);
        }
    
        public virtual int ProCus_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProCus_Delete", idParameter);
        }
    
        public virtual ObjectResult<ProCus_ReadOne_Result> ProCus_ReadOne(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProCus_ReadOne_Result>("ProCus_ReadOne", idParameter);
        }
    
        public virtual int ProCus_Update(Nullable<int> id, string email, string password, string firstName, string lastName, string image, Nullable<System.DateTime> birth, Nullable<int> id_Gender, string phone, string address, Nullable<int> id_Role)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            var birthParameter = birth.HasValue ?
                new ObjectParameter("birth", birth) :
                new ObjectParameter("birth", typeof(System.DateTime));
    
            var id_GenderParameter = id_Gender.HasValue ?
                new ObjectParameter("id_Gender", id_Gender) :
                new ObjectParameter("id_Gender", typeof(int));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var id_RoleParameter = id_Role.HasValue ?
                new ObjectParameter("id_Role", id_Role) :
                new ObjectParameter("id_Role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProCus_Update", idParameter, emailParameter, passwordParameter, firstNameParameter, lastNameParameter, imageParameter, birthParameter, id_GenderParameter, phoneParameter, addressParameter, id_RoleParameter);
        }
    
        public virtual ObjectResult<ProCheck_U_Result> ProCheck_U(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProCheck_U_Result>("ProCheck_U", emailParameter);
        }
    
        public virtual ObjectResult<ProLogin_Result> ProLogin(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProLogin_Result>("ProLogin", emailParameter, passwordParameter);
        }
    
        public virtual int ProMes_Create(Nullable<int> id_Bill, string sender, string mes)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProMes_Create", id_BillParameter, senderParameter, mesParameter);
        }
    
        public virtual ObjectResult<ProMes_Read_Result> ProMes_Read(Nullable<int> id_Bill, string sender, string mes)
        {
            var id_BillParameter = id_Bill.HasValue ?
                new ObjectParameter("id_Bill", id_Bill) :
                new ObjectParameter("id_Bill", typeof(int));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProMes_Read_Result>("ProMes_Read", id_BillParameter, senderParameter, mesParameter);
        }
    
        public virtual ObjectResult<Pro_ReadShop_Result> Pro_ReadShop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_ReadShop_Result>("Pro_ReadShop");
        }
    
        public virtual ObjectResult<ProCus_ReadMulti_Result2> ProCus_ReadMulti()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProCus_ReadMulti_Result2>("ProCus_ReadMulti");
        }
    
        public virtual ObjectResult<ProBill_ReadAll_Result> ProBill_ReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProBill_ReadAll_Result>("ProBill_ReadAll");
        }
    
        public virtual ObjectResult<ProBou_ByCus_Result> ProBou_ByCus(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProBou_ByCus_Result>("ProBou_ByCus", idParameter);
        }
    
        public virtual ObjectResult<ProBouReadAll_Result> ProBouReadAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProBouReadAll_Result>("ProBouReadAll");
        }
    }
}
