//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admination
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id_Mess { get; set; }
        public int Id_Bill { get; set; }
        public string Sender { get; set; }
        public string Message1 { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
