//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admination
{
    using System;
    
    public partial class ProCus_ReadMulti_Result2
    {
        public int Id_Cus { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Image { get; set; }
        public Nullable<int> Id_Gender { get; set; }
        public string Gender_Define { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Id_Role { get; set; }
        public string Role_Define { get; set; }
    }
}
